version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=ContrateLucasComoDeveJunior01
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - lojared

  loja-api:
    build:
      context: .
      dockerfile: src/LojaDoSeuManoel.API/Dockerfile
    container_name: loja-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__LojaDoSeuManoelConnection=Server=sqlserver;Database=LojaDoSeuManoel;User Id=sa;Password=ContrateLucasComoDeveJunior01;TrustServerCertificate=True;
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - lojared

networks:
  lojared:
    driver: bridge
