version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=ContrateLucasComoDeveJunior01
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    networks:
      - lojared
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/1433'"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 40s

  loja-api:
    build:
      context: .
      dockerfile: src/LojaDoSeuManoel.API/Dockerfile
    container_name: lojaDoSeuManoel-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__LojaDoSeuManoelConnection=Server=sqlserver;Database=LojaDoSeuManoel;User Id=sa;Password=ContrateLucasComoDeveJunior01;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    depends_on:
       sqlserver:
        condition: service_healthy
    networks:
      - lojared

networks:
  lojared:
    driver: bridge